### ISSUE TITLE
skipped rounds to be recast as 0 redundancy

### ISSUE THREAD

**Issue by significance** [ethersphere/storage-incentives#116]
at present, the price oracle does not amend the price in the event of skipped rounds (i.e. redundancy = 0)

in the event there are no applicants for a round, the round is 'skipped' and the the price oracle should increase the price by the inverse amount of redundancy = 8.

current price modulating numerator array:

`[0, 1036, 1027, 1025, 1024, 1023, 1021, 1017, 1012]`

proposed:

`[1036, 1031, 1027, 1025, 1024, 1023, 1021, 1017, 1012]`

as there are no transaction in the event there are no applicants, the price oracle should remember the last round number during which the price was modulated, and, when the next transaction happens, apply the relevant price change for each of the interstitial skipped rounds.

**Comment by n00b21337** [comment]
Sounds fine to me. On that note, I might found a bug in the current Redistribution contract ties to Oracle and Stamp. 
Line `OracleContract.adjustPrice(uint256(k));` could be the problem
as in adjustPrice there is a
`require(redundancy > 0, "unexpected zero");`

which means if k is 0, then adjustPrice is reverted which also reverts the **claim** call in redistribution contract. I wonder if this is meant to be like that?

A similar pattern is with PostageContract.withdraw(winner.owner);  which has
require(ERC20(bzzToken).transfer(beneficiary, totalAmount), "failed transfer");
which also could fail, meaning again the whole **claim** process is failing and all the house keeping in it.

This can be fixed with try/catch pattern. Just need to know what do we exactly want and do we want to fail the claim in those cases or not?

**Comment by significance** [comment]
in the future, the plan is to note skipped rounds and then apply a price increase for each one skipped

**Comment by n00b21337** [comment]
Ok, that makes sense. About the withdraw, possibly it could fail but very unlikely. So we can keep it like it is now.

**Comment by n00b21337** [comment]
My understanding of the setup is that we have this code, which prevents us from get into to setPrice when there are no reveals.
And if there are reveals there are commits and if there are commits then there is redundancy as its basically value of K which is the value of the number of LEGIT commits. So unless we have commits and reveals that are wrong we don't have a chance to set a price. Which seems to me that it could be a problem as we want to increase a price if there is no one commitng and claimaing as well as when there are wrong commits/claims,  thoughs @significance  ?

```
    function claim() external whenNotPaused {
        require(currentPhaseClaim(), "not in claim phase");
        uint256 cr = currentRound();
        require(cr == currentRevealRound, "round received no reveals");
```

the other situation is that there are

**Comment by n00b21337** [comment]
Deployed with latest price oracle
