### ISSUE TITLE
automatize code conventions

### ISSUE THREAD

**Issue by nugaon** [ethersphere/storage-incentives#169]
The eslint and prettier are configured but yet the codebase gets several style related corrections.
It could be avoided if the style check was added to the CI tests.
The errors should appear in the IDEs automatically in case of wrong formatting (e.g. spacing, unnecessary break lines, etc.).

**Comment by n00b21337** [comment]
Was kind of mentioned here as well but this idea above is better and long term solution.
https://github.com/ethersphere/storage-incentives/issues/136

Currently, the problem is that ppl that worked on the codebase didn't have set **autoformat on save** or at least do formatting before committing and nothing did enforce them to do so.

**Comment by nugaon** [comment]
so that's why I said the linter should show error on places where we do not agree on the formatting. any other formatting should be ignored in PRs that is not `style` related

**Comment by n00b21337** [comment]
Solved here
https://github.com/ethersphere/storage-incentives/pull/183/files
